import { useCallback, useEffect, useRef, useState } from "react";
import { getBearerToken } from "@/lib/auth/client";
import { getCustomerChat, readCustomerChat, sendCustomerChat } from "@/lib/toranj/api/messages";
import type { Message } from "@/lib/toranj/types";

export function CustomerMessenger() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [text, setText] = useState("");
  const [shopName, setShopName] = useState("ترنج");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const lastEventId = useRef(0);
  const seen = useRef(new Set<number>());
  const load = useCallback(async () => { try { const chat = await getCustomerChat(); setMessages(chat.messages); setShopName(chat.shopName || "ترنج"); } catch (e) { setError(e instanceof Error ? e.message : "پیام‌ها دریافت نشدند."); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { let closed = false; let controller: AbortController | null = null; async function connect() { while (!closed) { controller = new AbortController(); try { const headers: Record<string,string> = {}; const token = getBearerToken(); if (token) headers.Authorization = `Bearer ${token}`; const res = await fetch(`/api/events?after=${lastEventId.current}`, { headers, signal: controller.signal }); if (!res.ok || !res.body) throw new Error("sse"); const reader = res.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!closed) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const chunks = buffer.split("\n\n"); buffer = chunks.pop() ?? ""; for (const chunk of chunks) { const line = chunk.split("\n").find((v) => v.startsWith("data:")); if (!line) continue; const event = JSON.parse(line.slice(5).trim()) as { id?: number; type?: string }; if (event.id) { if (seen.current.has(event.id)) continue; seen.current.add(event.id); lastEventId.current = Math.max(lastEventId.current, event.id); } if (event.type === "message.created") void load(); } } } catch { if (closed || controller.signal.aborted) return; await new Promise((r) => setTimeout(r, 2500)); } } } void connect(); return () => { closed = true; controller?.abort(); }; }, [load]);
  async function send() { const body = text.trim(); if (!body || busy) return; setBusy(true); setError(""); try { const message = await sendCustomerChat({ data: { body } }); setMessages((current) => [...current.filter((m) => m.id !== message.id), message]); setText(""); } catch (e) { setError(e instanceof Error ? e.message : "ارسال پیام ناموفق بود."); } finally { setBusy(false); } }
  return <><button type="button" aria-label="پیام به ترنج" onClick={() => { setOpen(true); void readCustomerChat(); }} className="fixed bottom-[calc(5.75rem+env(safe-area-inset-bottom))] right-4 z-30 grid size-14 place-items-center rounded-full bg-brand text-brand-fg shadow-lg">💬</button>{open ? <div className="fixed inset-0 z-40 flex items-end justify-center bg-black/25 p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]"><section className="flex max-h-[82dvh] w-full max-w-md flex-col overflow-hidden rounded-3xl bg-surface shadow-2xl" dir="rtl"><header className="flex items-center justify-between border-b border-line px-4 py-3"><div><h2 className="font-bold">پیام‌رسان ترنج</h2><p className="text-xs text-ink-soft">گفتگو با {shopName}</p></div><button type="button" className="grid size-10 place-items-center rounded-xl bg-paper-2" onClick={() => setOpen(false)}>×</button></header><div className="min-h-48 flex-1 space-y-2 overflow-y-auto px-4 py-3">{messages.length === 0 ? <div className="grid min-h-48 place-items-center text-center text-sm text-ink-soft">هنوز پیامی ندارید.<br/>پیام خود را برای فروشنده ترنج ارسال کنید.</div> : messages.map((m) => <div key={m.id} className={`flex ${m.senderRole === "customer" ? "justify-start" : "justify-end"}`}><div className={`max-w-[82%] rounded-2xl px-3 py-2 text-sm ${m.senderRole === "customer" ? "bg-brand text-brand-fg" : "bg-paper-2 text-ink"}`}><p className="whitespace-pre-wrap break-words">{m.body}</p></div></div>)}</div>{error ? <p className="px-4 pb-2 text-xs text-brand">{error}</p> : null}<div className="flex gap-2 border-t border-line p-3"><textarea value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} rows={2} maxLength={2000} placeholder="پیام خود را بنویسید…" className="min-h-11 flex-1 resize-none rounded-xl border border-line bg-paper px-3 py-2 outline-none"/><button type="button" disabled={busy || !text.trim()} onClick={() => void send()} className="self-end rounded-xl bg-brand px-4 py-3 text-sm font-semibold text-brand-fg disabled:opacity-50">{busy ? "…" : "ارسال"}</button></div></section></div> : null}</>;
}
