import { createServerFn } from "@tanstack/react-start";
import { authMiddleware } from "@/lib/auth/middleware";
import { z } from "zod";

const itemSchema = z.object({ name: z.string().min(1), weight: z.number().nullable().optional(), quantity: z.number().nullable().optional(), unit: z.string().optional(), notes: z.string().optional() });
async function getDefaultShopCode(): Promise<string> { const { getSql } = await import("@/lib/db"); const sql = await getSql(); const rows = await sql<{ public_code: string }>`select public_code from shops order by created_at asc limit 1`; if (!rows[0]?.public_code) throw new Error("فروشگاه ترنج هنوز راه‌اندازی نشده است."); return rows[0].public_code; }
export const getCustomerState = createServerFn({ method: "GET" }).middleware([authMiddleware]).handler(async ({ context }) => { const { getSql } = await import("@/lib/db"); const { mapCustomer } = await import("../server/map"); const { publicShopView } = await import("../server/shop"); const sql = await getSql(); const rows = await sql<Record<string, unknown>>`select * from customers where user_id = ${context.userId} order by updated_at desc limit 1`; const customer = rows[0] ? mapCustomer(rows[0]) : null; const code = customer?.shopId ? String((await sql<{ public_code: string }>`select public_code from shops where id = ${customer.shopId} limit 1`)[0]?.public_code ?? "") : await getDefaultShopCode(); if (!code) throw new Error("فروشگاه ترنج پیدا نشد."); return { customer, shop: await publicShopView(code) }; });
export const registerCustomer = createServerFn({ method: "POST" }).middleware([authMiddleware]).validator(z.object({ firstName: z.string(), lastName: z.string(), phone: z.string(), address: z.string().optional() })).handler(async ({ context, data }) => { const { registerCustomerFromApp } = await import("../server/customers"); return registerCustomerFromApp({ shopCode: await getDefaultShopCode(), firstName: data.firstName, lastName: data.lastName, phone: data.phone, address: data.address, userId: context.userId }); });
export const createCustomerOrder = createServerFn({ method: "POST" }).middleware([authMiddleware]).validator(z.object({ items: z.array(itemSchema).min(1), notes: z.string().optional(), totalAmount: z.number().nullable().optional() })).handler(async ({ context, data }) => { const { getSql } = await import("@/lib/db"); const { mapCustomer } = await import("../server/map"); const { createOrderFromCustomer } = await import("../server/orders"); const sql = await getSql(); const rows = await sql<Record<string, unknown>>`select * from customers where user_id = ${context.userId} order by updated_at desc limit 1`; if (!rows[0]) throw new Error("ابتدا اطلاعات مشتری را ثبت کنید."); const customer = mapCustomer(rows[0]); const shop = await sql<{ public_code: string }>`select public_code from shops where id = ${customer.shopId} limit 1`; if (!shop[0]?.public_code) throw new Error("فروشگاه ترنج پیدا نشد."); return createOrderFromCustomer({ shopCode: shop[0].public_code, phone: customer.phone, firstName: customer.firstName, lastName: customer.lastName, userId: context.userId, items: data.items, notes: data.notes, totalAmount: data.totalAmount }); });
export const listCustomerOrders = createServerFn({ method: "GET" }).middleware([authMiddleware]).handler(async ({ context }) => { const { getSql } = await import("@/lib/db"); const { mapItem } = await import("../server/map"); const sql = await getSql(); const orders = await sql<Record<string, unknown>>`select o.* from orders o join customers c on c.id = o.customer_id where c.user_id = ${context.userId} order by o.created_at desc limit 300`; if (!orders.length) return []; const ids = orders.map((row) => String(row.id)); const items = await sql<Record<string, unknown>>`select * from order_items where order_id = any(${ids}::text[]) order by sort_order asc`; const byOrder = new Map<string, ReturnType<typeof mapItem>[]>(); for (const row of items) { const item = mapItem(row); const list = byOrder.get(item.orderId) ?? []; list.push(item); byOrder.set(item.orderId, list); } return orders.map((row) => ({ id: String(row.id), status: String(row.status), notes: String(row.notes ?? ""), totalAmount: row.total_amount == null ? null : Number(row.total_amount), paymentStatus: String(row.payment_status ?? "unpaid"), source: String(row.source ?? "customer_app"), createdAt: String(row.created_at), updatedAt: String(row.updated_at), items: byOrder.get(String(row.id)) ?? [] })); });
export const submitCustomerPayment = createServerFn({ method: "POST" }).middleware([authMiddleware]).validator(z.object({ orderId: z.string().optional(), amount: z.number().nullable().optional(), receiptNote: z.string().optional() })).handler(async ({ context, data }) => { const { getSql } = await import("@/lib/db"); const { recordPayment } = await import("../server/orders"); const sql = await getSql(); const rows = await sql<{ customer_id: string; shop_id: string }>`select c.id as customer_id, c.shop_id from customers c where c.user_id = ${context.userId} limit 1`; if (!rows[0]) throw new Error("ابتدا اطلاعات مشتری را ثبت کنید."); if (data.orderId) { const allowed = await sql`select 1 from orders where id = ${data.orderId} and customer_id = ${rows[0].customer_id} limit 1`; if (!allowed[0]) throw new Error("سفارش انتخاب‌شده متعلق به شما نیست."); } const paymentId = await recordPayment({ shopId: rows[0].shop_id, customerId: rows[0].customer_id, orderId: data.orderId ?? null, amount: data.amount ?? null, receiptNote: data.receiptNote, status: "pending" }); if (data.orderId) await sql`update orders set payment_status = 'pending', updated_at = now() where id = ${data.orderId} and customer_id = ${rows[0].customer_id}`; return { paymentId }; });
