/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// Customer routes are included here so typecheck works before the next router generation.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as CustomerRouteImport } from './routes/c'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicMessagesRouteImport } from './routes/api/public/messages'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'
import { Route as ApiPublicShopRouteImport } from './routes/api/public/shop'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({ id: '/customer-login', path: '/customer-login', getParentRoute: () => rootRouteImport } as any)
const CustomerRoute = CustomerRouteImport.update({ id: '/c', path: '/c', getParentRoute: () => rootRouteImport } as any)
const ApiEventsRoute = ApiEventsRouteImport.update({ id: '/api/events', path: '/api/events', getParentRoute: () => rootRouteImport } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({ id: '/api/health', path: '/api/health', getParentRoute: () => rootRouteImport } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({ id: '/api/auth/$', path: '/api/auth/$', getParentRoute: () => rootRouteImport } as any)
const ApiPublicMessagesRoute = ApiPublicMessagesRouteImport.update({ id: '/api/public/messages', path: '/api/public/messages', getParentRoute: () => rootRouteImport } as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({ id: '/api/public/orders', path: '/api/public/orders', getParentRoute: () => rootRouteImport } as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({ id: '/api/public/register', path: '/api/public/register', getParentRoute: () => rootRouteImport } as any)
const ApiPublicShopRoute = ApiPublicShopRouteImport.update({ id: '/api/public/shop', path: '/api/public/shop', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customer-login': typeof CustomerLoginRoute
  '/c': typeof CustomerRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/shop': typeof ApiPublicShopRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById extends FileRoutesByFullPath {
  __root__: typeof rootRouteImport
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: '__root__' | keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerRoute: typeof CustomerRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicMessagesRoute: typeof ApiPublicMessagesRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiPublicShopRoute: typeof ApiPublicShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/customer-login': { id: '/customer-login'; path: '/customer-login'; fullPath: '/customer-login'; preLoaderRoute: typeof CustomerLoginRouteImport; parentRoute: typeof rootRouteImport }
    '/c': { id: '/c'; path: '/c'; fullPath: '/c'; preLoaderRoute: typeof CustomerRouteImport; parentRoute: typeof rootRouteImport }
    '/api/events': { id: '/api/events'; path: '/api/events'; fullPath: '/api/events'; preLoaderRoute: typeof ApiEventsRouteImport; parentRoute: typeof rootRouteImport }
    '/api/health': { id: '/api/health'; path: '/api/health'; fullPath: '/api/health'; preLoaderRoute: typeof ApiHealthRouteImport; parentRoute: typeof rootRouteImport }
    '/api/auth/$': { id: '/api/auth/$'; path: '/api/auth/$'; fullPath: '/api/auth/$'; preLoaderRoute: typeof ApiAuthSplatRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/messages': { id: '/api/public/messages'; path: '/api/public/messages'; fullPath: '/api/public/messages'; preLoaderRoute: typeof ApiPublicMessagesRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/orders': { id: '/api/public/orders'; path: '/api/public/orders'; fullPath: '/api/public/orders'; preLoaderRoute: typeof ApiPublicOrdersRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/register': { id: '/api/public/register'; path: '/api/public/register'; fullPath: '/api/public/register'; preLoaderRoute: typeof ApiPublicRegisterRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/shop': { id: '/api/public/shop'; path: '/api/public/shop'; fullPath: '/api/public/shop'; preLoaderRoute: typeof ApiPublicShopRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, LoginRoute, CustomerLoginRoute, CustomerRoute,
  ApiEventsRoute, ApiHealthRoute, ApiAuthSplatRoute,
  ApiPublicMessagesRoute, ApiPublicOrdersRoute, ApiPublicRegisterRoute, ApiPublicShopRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
